## Array

In [22]:
import numpy as np

x = [1,2,3,4] 

y = np.array(x)

print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [23]:
l = []

for i in range(1, 5):
    int_1 = input("Enter: ")
    l.append(int_1)
print(l)  #list element are separeted by (,) or comma
print(np.array(l))   #list element are separeted by ( ) space

Enter: 3
Enter: 5
Enter: 7
Enter: 3
['3', '5', '7', '3']
['3' '5' '7' '3']


## ---Dimensions in Arrays---

### 1-D Array

In [36]:
x = np.array([1,2,3,4,5])

print(f"Dimention of {x} is {x.ndim}")

Dimention of [1 2 3 4 5] is 1


### 2-D Array

In [44]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(f"Dimention of \n{y} is {y.ndim}")

Dimention of 
[[1 2 3]
 [4 5 6]
 [7 8 9]] is 2


### 3-D Array 

In [59]:
z = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(f"Dimention of \n{z} is {z.ndim}")

Dimention of 
[[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 3


### n-D Array

In [60]:
n = np.array([1,2,3,4], ndmin = 10)
print(n)
print(n.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
