# ---Spacial NumPy Array---

### Array filled with 0's

In [2]:
import numpy as np

In [13]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero,"\n")
print(ar_zero1)

[0. 0. 0. 0.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Array filled with 1's

In [18]:
ar_one = np.ones(4)
ar_one1 = np.ones((2, 5))

print(ar_one,"\n")
print(ar_one1)

[1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Create an empty array

In [20]:
ar_em = np.empty(4)

print(ar_em)

[1. 1. 1. 1.]


### An array with a range of elements

In [22]:
ar_rn = np.arange(4)

print(ar_rn)

[0 1 2 3]


### Array diagonal element filled with 1's 

In [27]:
ar_dia = np.eye(3)
ar_dia1 = np.eye(3,5)

print(ar_dia,"\n")
print(ar_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Create an array with values that are spaced linearly in a spacified interval 

In [29]:
ar_lin = np.linspace(1,10, num = 5)

print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
