# ---Create NumPy Array with Random Number---

## Random 
### rand():The function is used to generate a random value between 0 t 1

In [7]:
import numpy as np

In [8]:
var = np.random.rand(4)   # random number will be in 0 to 1

print(var)

[0.09100686 0.64264568 0.13515339 0.81229788]


In [9]:
var1 = np.random.rand(2,5) 

print(var1)

[[0.13082997 0.41675064 0.37589041 0.06376294 0.86456386]
 [0.44426163 0.22137705 0.86175902 0.99827227 0.14068798]]


### -- randn(): The function is used to generate a random value close to zero. This may return positive or negative numbers as well.

In [14]:
var2 = np.random.randn(5)

print(var2)

[-1.60007186 -1.03172431  0.42197123 -0.32152775  0.14483737]


### -- ranf(): The function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half open interval [0.0, 1.0)

In [16]:
var3 = np.random.ranf(4)

print(var3)

[0.7076749  0.12312937 0.52525608 0.6916701 ]


### -- randint(): The function is used to generate a random number between a given range.

In [40]:
# randint_array = np.random.randint(min, max, total value)

var4 = np.random.randint(14, 19, 13)

print(var4)

[16 15 15 14 16 15 16 16 16 16 16 15 15]
