# Arithmetic Operation in NumPy Arrays

####  a+b = np.add(a,b)
####  a-b = np.subtract(a,b)
####  a*b = np.multiply(a,b)
####  a/b = np.divide(a,b)
####  a%b = np.mod(a,b)
####  a**b = np.power(a,b)
####  1/a = np.reciprocal(a)

In [3]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd1 = var1 + var2
print(varadd1)

[2 4 6 8]


In [7]:
var3 = np.array([21, 30, 33, 99])

varsub = var3 / 3

print(varsub)

[ 7. 10. 11. 33.]


In [9]:
var4 = np.array([21, 30, 33, 99])

varmod = var4 % 5
print(varmod)

[1 0 3 4]


In [11]:
var5 = np.array([2, 3, 13, 9])

varpow = var5 ** 2
print(varpow)

[  4   9 169  81]


## 2-D Array

In [12]:
var6 = np.array([[1,2,3,4],[4,3,4,1]])
var7 = np.array([[0,7,2,5],[5,2,4,8]])

varadd2 = var6 + var7
print(varadd2)

[[1 9 5 9]
 [9 5 8 9]]
