# Shape & Reshaping in NumPy Arrays


## Shape

In [2]:
import numpy as np

In [7]:
var = np.array([[1,2,7,4],[1,2,3,5]])

print(var)
print()
print(var.shape)

[[1 2 7 4]
 [1 2 3 5]]

(2, 4)


In [9]:
var1 = np.array([1,2,3,4], ndmin = 4)

print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


## Reshape

In [19]:
var2 = np.array([1,2,3,4,5,6,7,8,9,10, 11,12])
print(var2)
print(var2.ndim)

x = var2.reshape(2, 3 , 2)
print(x)
print(x.ndim)
print()

y = x.reshape(-1)
print(y)
print(y.ndim)
print(y.shape)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
