# Broadcasting

In [2]:
import numpy as np

In [3]:
var1 = np.array([1,2,3,4])

var2 = np.array([2,3,4])

print(var1 + var2)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [17]:
var3 = np.array([1,2,3])
print(var3)
print(var3.shape)
print(var3.ndim)
print()

var4 = np.array([[1],[2],[3]])
print(var4)
print(var4.shape)
print(var4.ndim)
print()

var5 = np.array([[1,2],[2,4],[3,7]])
print(var5)
print(var5.shape)
print(var5.ndim)
print()

print(var3 + var4)
print((var3 + var4).shape)
print((var3 + var4).ndim)

[1 2 3]
(3,)
1

[[1]
 [2]
 [3]]
(3, 1)
2

[[1 2]
 [2 4]
 [3 7]]
(3, 2)
2

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)
2


In [23]:
x = np.array([[1],[2]])
print(x)
print(x.shape)
print(x.ndim)
print()

y = np.array([[1,2,3],[1,2,3]])
print(y)
print(y.shape)
print(y.ndim)
print()


print(x+y)

[[1]
 [2]]
(2, 1)
2

[[1 2 3]
 [1 2 3]]
(2, 3)
2

[[2 3 4]
 [3 4 5]]
