# Indexing NumPy Arrays

In [2]:
import numpy as np

In [4]:
x = np.array([3,4,6,9])
#  positive   0,1,2,3
#  negetive -4,-3,-2,-1

print(x[3])
print(x[-2])


9
6


In [6]:
y = np.array([[8,6,5],[1,2,3]])

print(y)
print(y.ndim)

[[8 6 5]
 [1 2 3]]
2


In [29]:
z = np.array([[1,2,3],[5,6,7]])

print(z)
print(z[1,1])

[[1 2 3]
 [5 6 7]]
6


# Slicing NumPy Arrays

##### x = [1,2,3,4,] 
##### x[start:stop:step]

In [24]:
a = np.array([1,2,3,4,5,6,7])
# index       0,1,2,3,4,5,6

print(a)
print()
print("2 to 5:", a[1:5:2])
print("2 to end", a[1:])
print("start to 5:", a[:5])
print("step:", a[::3])

[1 2 3 4 5 6 7]

2 to 5: [2 4]
2 to end [2 3 4 5 6 7]
start to 5: [1 2 3 4 5]
step: [1 4 7]
