# Iteration NumPy Arrays


In [2]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5,6,7,8,9])

for i in x:
    print(i)

1
2
3
4
5
6
7
8
9


In [14]:
y = np.array([[1,2,3,4],[5,6,7,8]])
print(y)

print()

for i in y:
    for j in i:
        print(j)


[[1 2 3 4]
 [5 6 7 8]]

1
2
3
4
5
6
7
8


### np.nditer

In [20]:
z = np.array([[[1,2,3,4],[5,6,7,8]]])
print(z)

print()

for i in np.nditer(z, flags=['buffered'], op_dtypes=['S']):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


### np.ndenumerate()

In [22]:
a = np.array([[[1,2,3,4],[5,6,7,8]]])
print(a)

print()

for index,data in np.ndenumerate(a):
    print(index, data)

[[[1 2 3 4]
  [5 6 7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
