# Copy & View

In [9]:
import numpy as np

### Copy

##### * The copy owns the data
##### * The copy of an array is a new array
##### * The changes made in the copy data does not reflect in the original array

In [18]:
x = np.array([1,2,3,4,4,5,7])

cp = x.copy()

x[2] = 13

print(x)
print(cp)

[ 1  2 13  4  4  5  7]
[1 2 3 4 4 5 7]


### View

##### * The view does not own the data
##### * A view of the original array
##### *Any changes made to theview will affect the original array,
##### *And any changes made to the origin array afect the view

In [17]:
y = np.array([1,2,3,4,6,4,2])

vi = x.view()

y[2] = 13

print(y)
print(vi)

[ 1  2 13  4  6  4  2]
[ 1  2 13  4]
