# Join & Split

### Join Array: Joining means putting contents of two or more arrays in a single array.

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

ar = np.concatenate((x,y))
print(ar)

[1 2 3 4 5 6 7 8]


In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

ar1 = np.concatenate((a,b), axis = 0)
print(ar1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Stack

In [5]:
a1 = np.array([1,2,3,4])
b2 = np.array([5,6,7,8])

ar2 = np.hstack((a1,b2))  # work to row
ar3 = np.vstack((a1,b2))  # work to column
ar4 = np.dstack((a1,b2))  # work to hight

print(ar2)
print(ar3)
print(ar4)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


### Split 

In [9]:
o = np.array([1,2,3,4,5,6])
print(o)
arr = np.array_split(o,3)
print(arr)
print(type(arr))



[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [14]:
p = np.array([[1,2],[3,4],[5,6]])
print(p)
arr1 = np.array_split(p,3)
arr2 = np.array_split(p,3, axis = 1)

print(arr1)
print(arr2)
print(type(arr))

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>
