# Search, Sort, Search Sorted, Filter

### Search Array: Search an array for a certain value, and return the indexes that get a match.

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,2,3,4,6])
#             0,1,2,3,4,5,6,7,8
x = np.where(a == 2)

print(x)

(array([1, 5], dtype=int64),)


### Search Sorted Array: Which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order

In [7]:
b = np.array([1,2,3,4,5,6,7,8,9])
#             0,1,2,3,4,5,6,7,8
x1 = np.searchsorted(b, 5)   # where the number 5 can be seat(L->R)
x2 = np.searchsorted(b, [5,7,1], side='right')   # where the number 5 can be seat(L->R)

print(x1)
print(x2)

4
[5 7 1]


### Sort Array: Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending

In [10]:
c = np.array([11,21,3,40,15,26,37,8,-9])
#             0,1,2,3,4,5,6,7,8

d = np.array(['r','a','f','i'])

x_s = np.sort(c)
x_ss = np.sort(d)

print(x_s)
print(x_ss)

[-9  3  8 11 15 21 26 37 40]
['a' 'f' 'i' 'r']


### Filter Array: Getting some elements out of an existing array and creating a new array out of them

In [12]:
e = np.array(['r','a','f','i'])

f = [True, False, False, True]

na = e[f]

print(na)

['r' 'i']


# Shuffle, Unique, Resize, Flatten, Ravel

### Shuffle

In [18]:
x1 = np.array([1,2,3,4,5,6])

np.random.shuffle(x1)

print(x1)

[5 6 1 4 3 2]


### Unique

In [23]:
x2 = np.array([1,2,3,6,4,2,1,3,4,5,6,5,4,2,2,1])

o = np.unique(x2, return_index = True, return_counts = True)

print(o)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 4, 9, 3], dtype=int64), array([3, 4, 2, 3, 2, 2], dtype=int64))


### Resize

In [29]:
x3 = np.array([1,2,3,4,5,6,7])
x4 = np.array([0,1])

y = np.resize(x3, (3,3))
y1 = np.resize(x4, (3,3))

print(y)
print()
print(y1)

[[1 2 3]
 [4 5 6]
 [7 1 2]]

[[0 1 0]
 [1 0 1]
 [0 1 0]]


### Flatten & Ravel

In [37]:
x5 = np.array([1,2,3,4,5,6,7])
y2 = np.resize(x3, (3,3))
print(y2)
print()
print("Flatten: ",y2.flatten(order='F'))
print("Ravel: ",np.ravel(y2,order='F') )



[[1 2 3]
 [4 5 6]
 [7 1 2]]

Flatten:  [1 4 7 2 5 1 3 6 2]
Ravel:  [1 4 7 2 5 1 3 6 2]
