# Insert and Delete Fucntion

### Insert

In [18]:
import numpy as np

ModuleNotFoundError: No module named 'pands'

In [7]:
a = np.array([1,2,3,4,6,89,2,0])

print(a)
print(type(a))

# np.insert(array, index, data)

x1 = np.insert(a, (2,4), 40)
print(x1)

[ 1  2  3  4  6 89  2  0]
<class 'numpy.ndarray'>
[ 1  2 40  3  4 40  6 89  2  0]


In [13]:
b = np.array([[1,2,3,4],[6,89,2,0]])
bi=np.insert(b,2,[5,3],axis=1)

print(bi)

[[ 1  2  5  3  4]
 [ 6 89  3  2  0]]


In [25]:
b = np.array([[1,2,3,4],[6,89,2,0]])
x2 = np.append(b, 5.7)
print(x2)

[ 1.   2.   3.   4.   6.  89.   2.   0.   5.7]
