# Matrix in NumPy Array

### Create matrix 

In [2]:
import numpy as np

In [9]:
var = np.matrix([[1,2,3],[4,5,6]])

print("Matrix: ",var)
print(type(var))

Matrix:  [[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [10]:
var1 = np.array([[1,2,3],[4,5,6]])

print("Array: ",var1)
print(type(var1))

Array:  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Arithmetic operation in matrix

In [18]:
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
y = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print("add: \n", x+y)
print("sub: \n", x-y)
print("mul: \n", x*y)  # is called dot multiplication
print(x.dot(y))



add: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
sub: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
mul: 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Matrix Function in Numpy

### * Transpose
### * Swapaxes
### * Inverse
### * Power
### * Determinate

In [38]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(a)
print()
print(np.transpose(a))
# or 
print()
print(a.T)
print()
print(np.swapaxes(a,0,1))
print()

# inverse matrix
b = np.matrix([[1,2],[3,4]])
print(b)
print()
print(np.linalg.inv(b))

# power matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [39]:
o = np.matrix([[1,2],[3,4]])
print(o)
print()
print(np.linalg.matrix_power(o,2))
print()
print(np.linalg.matrix_power(o,0))
print()
print(np.linalg.matrix_power(o,-1))

# determenate
print(np.linalg.det(o))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


## Arithmetic operation in array

In [19]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
y1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("add: \n", x1+y1)
print("sub: \n", x1-y1)
print("mul: \n", x1*y1)

add: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
sub: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
mul: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
